### ISSUE TITLE
Does Tin Ore Spawn at all?

### ISSUE THREAD

**Issue by WilxGaming** [TheLimePixel/Vanilla-Expert-Mode#2]
I know tin ore looks almost identical to stone, But it doesn't even show up with the tool tip. I went into creative and mined for an hour, covering thousands of blocks with no tin ore to be found. Lots of copper and other things, but no tin.

On a side note, making Silver and Tin that hard to see is being cruel to people with bad eyesight.

**Comment by TheLimePixel** [comment]
Tin spawns below level 36, but now that I think about it, I'm going to change it to below 48.
